contact_links:
  - name: 🙌 Contribution Guide
    url: https://github.com/uchihamalolan/contribute
    about: Please read through before making contributions.
  - name: 💬 Malo's Discord Server
    url: https://chat.malolan.me/
    about: Want to discuss / chat with the community? Here you go!
